name: "Security Scan on PR"
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security_scan:
    runs-on: [self-hosted, linux, x64, big]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.1
      - name: Run CodeQL Scan
        uses: github/codeql-action/init@v3.35.1
        with:
          languages: 'python,javascript'
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3.35.1
